# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cc61f46cf1d6bc771a8c3ed2c486b2caa6605e970382bd84a3d44b3adfdb59ae1bc5221d4a76fe4f9fc5b05ccdb622d09e8e9fa5fecb69b5228b26334899f07

test:
  secret_key_base: a0ab55ddff2f47e96f4b937e1a72fb4a93ac233f0f6eaf13924d8bffee2a697272a2a0268ca6a296ae5f51dc3d9deca9f837f256762b1a0d00a2b60d193edf7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
